// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv'
import { defineConfig, env } from "prisma/config";

dotenv.config({ path: './.env.development.local' })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
